name: build
description: installs dependencies & generates a build

jobs:
  build:
    name: build dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: build
        run: npm run build
