/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import { IPoolDataProvider } from './IPoolDataProvider';

export class IPoolDataProviderFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IPoolDataProvider {
    return new Contract(address, _abi, signerOrProvider) as IPoolDataProvider;
  }
}

export const _abi = [
  {
    inputs: [
      {
        internalType: 'contract ILendingPoolAddressesProvider',
        name: 'provider',
        type: 'address',
      },
    ],
    name: 'getReservesData',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'underlyingAsset',
            type: 'address',
          },
          {
            internalType: 'string',
            name: 'name',
            type: 'string',
          },
          {
            internalType: 'string',
            name: 'symbol',
            type: 'string',
          },
          {
            internalType: 'uint8',
            name: 'decimals',
            type: 'uint8',
          },
          {
            internalType: 'bool',
            name: 'isActive',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'usageAsCollateralEnabled',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'borrowingEnabled',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'stableBorrowRateEnabled',
            type: 'bool',
          },
          {
            internalType: 'uint256',
            name: 'baseLTVasCollateral',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'averageStableBorrowRate',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'liquidityIndex',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'reserveLiquidationThreshold',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'reserveLiquidationBonus',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'variableBorrowIndex',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'variableBorrowRate',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'availableLiquidity',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'stableBorrowRate',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'liquidityRate',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'totalBorrowsStable',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'totalBorrowsVariable',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'totalLiquidity',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'utilizationRate',
            type: 'uint256',
          },
          {
            internalType: 'uint40',
            name: 'lastUpdateTimestamp',
            type: 'uint40',
          },
          {
            internalType: 'uint256',
            name: 'priceInEth',
            type: 'uint256',
          },
          {
            internalType: 'address',
            name: 'aTokenAddress',
            type: 'address',
          },
        ],
        internalType: 'struct IPoolDataProvider.ReserveData[]',
        name: '',
        type: 'tuple[]',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract ILendingPoolAddressesProvider',
        name: 'provider',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'user',
        type: 'address',
      },
    ],
    name: 'getUserReservesData',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'underlyingAsset',
            type: 'address',
          },
          {
            internalType: 'uint256',
            name: 'principalATokenBalance',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'userBalanceIndex',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'redirectedBalance',
            type: 'uint256',
          },
          {
            internalType: 'address',
            name: 'interestRedirectionAddress',
            type: 'address',
          },
          {
            internalType: 'bool',
            name: 'usageAsCollateralEnabledOnUser',
            type: 'bool',
          },
          {
            internalType: 'uint256',
            name: 'borrowRate',
            type: 'uint256',
          },
          {
            internalType: 'enum CoreLibrary.InterestRateMode',
            name: 'borrowRateMode',
            type: 'uint8',
          },
          {
            internalType: 'uint256',
            name: 'originationFee',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'principalBorrows',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'variableBorrowIndex',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'lastUpdateTimestamp',
            type: 'uint256',
          },
        ],
        internalType: 'struct IPoolDataProvider.UserReserveData[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
