export type BorrowTableItem = {
  id: string;
  symbol: string;
  underlyingAsset: string;
  currentBorrows: number | string;
  currentBorrowsInUSD: number | string;
  stableBorrowRate: number | string;
  variableBorrowRate: number | string;
  availableBorrows: number | string;
  availableBorrowsInUSD: number | string;
  stableBorrowRateEnabled?: boolean;
  userId?: string;
  isFreezed?: boolean;
  vincentivesAPR: string;
  sincentivesAPR: string;
  aincentivesAPR: string;
  borrowCap: string;
  isIsolated: boolean;
  borrowableInIsolation: boolean;
  totalBorrows: string;
};
